### ISSUE TITLE
`cpan-cve.pl` is not getting installed

### ISSUE THREAD

**Issue by abeltje** [CPAN-Security/Test-CVE#1]
I see the repository has a script `scripts/cpan-cve.pl` but it is not installed, perhaps add:
`EXE_FILES => [qw< scripts/cpan-cve.pl >],` to `WriteMakefile()` in `Makefile.PL`?

**Comment by Tux** [comment]
That is eventually the plan. Either in the way you suggest or with a question if installation is wanted, like in Spreadsheet::Read

Reason this is not yet the case is that we want to check if the script is ok as is or that it needs more, like Module::Build support (yuck), before promoting it.

**Comment by abeltje** [comment]
I just installed the module with the cpan client. Without installation of the script, I have no way of knowing the script was in the tarball, and was about to write it, until I looked at this repository and saw it's already here...
Imo it's fine to have this tiny wrapper around the actual code, so we can use it, even if it doesn't support `Build.PL` (yet).
